const conditionsList = [
  'alcoholism',
  'allergies',
  'alzheimer\'s',
  'amputation',
  'angioplasty / cabg',
  'aortic aneurysm',
  'appendicitis',
  'arthritis',
  'asthma',
  'atrial fibrillation',
  'autism',
  'bronchitis',
  'cancer',
  'cardiac',
  'CVA / TIA',
  'chronic back pain',
  'congestive heart failure',
  'COPD / emphysema',
  'coronary artery disease',
  'covid - 19(confirmed)',
  'dementia',
  'diabetes 1',
  'diabetes 2',
  'diverticulitis',
  'epiglottitis',
  'fall risk',
  'gastrointestinal disease',
  'gerd',
  'glaucoma',
  'hearing impaired',
  'hepatitis',
  'hernia',
  'HIV / aids',
  'hypertension',
  'implanted defibrillator',
  'liver disease',
  'meningitis',
  'migraines',
  'miocardio imfaction',
  'obesity',
  'osteoporosis',
  'Other',
  'pacemaker',
  'placenta abruptio',
  'placenta previa',
  'pneumonia',
  'preeclampsia',
  'pregnancy',
  'prescribed medications',
  'psychiatric',
  'pulmonary embolism',
  'renal failure',
  'seizure history',
  'sepsis',
  'sickle cell',
  'substance abuse',
  'tobacco use',
  'tuberculous',
  'ulcer',
  'Unknown',
  'visually impaired'
]

const jobsList = [
  'Medical Assistant',
  'Nursing Assistant',
  'Home Health Aide',
  'Licensed Practical Nurse',
  'Physician',
  'Therapist',
  'Registered Nurse',
  'Pharmacy Technician',
  'Diagnostic Medical Sonographer',
  'Clinical Laboratory Technician',
  'Dental Assistant',
  'Pharmacist',
  'Emergency Medical Technician',
  'Radiologic Technologist',
  'Physical Therapist',
  'Dental Hygienist',
  'Health Information Technician',
  'Clinical Laboratory Technologist',
  'Occupational Therapy Aide',
  'Speech-Language Pathologist',
  'Respiratory Therapist',
  'Family Practitioner',
  'Dentist',
  'Nurse Practitioner',
  'Occupational Therapist',
  'Phlebotomist',
  'Surgical Technologist',
  'Physician Assistant',
  'Veterinary Technologist',
  'Psychiatric Aide',
  'Medical Transcriptionist',
  'Occupational Health and Safety Specialist',
  'Laboratory Animal Caretaker',
  'Massage Therapist',
  'Physical Therapy Assistant',
  'Dispensing Optician',
  'Dietician',
  'Veterinarian',
  'Nursing Assistant & Orderlies',
  'Cardiovascular Technologist',
  'Medical Equipment Preparer',
  'Surgeon',
  'Nurse Anesthetist',
  'Pediatrician',
  'Anesthesiologist',
  'Magnetic Resonance Imaging Technologist',
  'Optometrist',
  'Chiropractor',
  'Psychiatrist',
  'Obstetrician'
]

module.exports = {
  conditions: conditionsList,
  jobs: jobsList
}
